apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spawner
spec:
  rules:
  - host: spawner.apps.example.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: spawner
          servicePort: 8080
